site_name: Programme Course Book
docs_dir: publish
site_dir: site
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.sections
  - navigation.expand
  - toc.integrate
markdown_extensions:
- tables
- toc
- admonition
- pymdownx.details
- pymdownx.superfences
nav:
- Home: index.md
- Advanced Data Science:
  - Advanced Decision Tree Concepts and Hyperparameter Tuning: modules/advanced-data-science/advanced-decision-tree-concepts-and-hyperparameter-tuning.md
- Ai And Ml:
  - Week 01:
    - Introduction to AI and Machine Learning: modules/ai-and-ml/week-01/session-01.md
- Pages:
  - Week 6 — Advanced Decision Tree Concepts and Hyperparameter Tuning: pages/week-6-advanced-decision-tree-concepts-and-hyperparameter-tuning.md
